name: task
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  equatable: ^2.0.5
  file_picker: ^6.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  loading_indicator: ^3.1.1
  pretty_dio_logger: ^1.3.1
  toast: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - .env
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
