class AppStrings {
  const AppStrings._();

  static const appName = 'Task';
  static const accountLogin = 'Account Login';
  static const emailAddress = 'Email Address';
  static const password = 'Password';
  static const confirmPassword = 'Confirm Password';
  static const rememberMe = 'Remember me';
  static const forgotPassword = 'Forgot Password?';
  static const login = 'Login';
  static const donnotHaveAnAccount = 'Don’t have an account ?';
  static const register = 'Register';
  static const completeData = 'Complete Data';
  static const firstName = 'First Name';
  static const lastName = 'Last Name';
  static const userType = 'User Type';
  static const next = 'Next';
  static const about = 'About';
  static const salary = 'Salary';
  static const gender = 'Gender';
  static const male = 'Male';
  static const female = 'Female';
  static const skills = 'Skills';
  static const enterYourSkill = 'Enter your skill';
  static const videoProduction = 'Video Production';
  static const favouriteSocialMedia = 'Favourite Social Media';
  static const submit = 'Submit';
  static const confirm = 'Confirm';
  static const facebook = 'Facebook';
  static const twitter = 'Twitter';
  static const linkedIn = 'LinkedIn';
  static const birthDate = 'Birth Date';
  static const sar = 'SAR';
  static const seller = 'Seller';
  static const buyer = 'Buyer';
  static const both = 'Both';
  static const whoAmI = 'Who Am I';
  static const countries = 'Countries';
  static const services = 'Services';
  static const popularServices = 'Popular Services';
  static const country = 'Country';
  static const capital = 'Capital';
}
